/**
 * DigitalTown SSO API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ClientUpdate1 {
  
  @SerializedName("userID")
  private String userID = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("redirect")
  private String redirect = null;
  @SerializedName("client_id")
  private String clientId = null;

  /**
   * User ID
   **/
  @ApiModelProperty(required = true, value = "User ID")
  public String getUserID() {
    return userID;
  }
  public void setUserID(String userID) {
    this.userID = userID;
  }

  /**
   * Name
   **/
  @ApiModelProperty(required = true, value = "Name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Redirect
   **/
  @ApiModelProperty(required = true, value = "Redirect")
  public String getRedirect() {
    return redirect;
  }
  public void setRedirect(String redirect) {
    this.redirect = redirect;
  }

  /**
   * Client ID
   **/
  @ApiModelProperty(required = true, value = "Client ID")
  public String getClientId() {
    return clientId;
  }
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientUpdate1 clientUpdate1 = (ClientUpdate1) o;
    return (this.userID == null ? clientUpdate1.userID == null : this.userID.equals(clientUpdate1.userID)) &&
        (this.name == null ? clientUpdate1.name == null : this.name.equals(clientUpdate1.name)) &&
        (this.redirect == null ? clientUpdate1.redirect == null : this.redirect.equals(clientUpdate1.redirect)) &&
        (this.clientId == null ? clientUpdate1.clientId == null : this.clientId.equals(clientUpdate1.clientId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userID == null ? 0: this.userID.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.redirect == null ? 0: this.redirect.hashCode());
    result = 31 * result + (this.clientId == null ? 0: this.clientId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientUpdate1 {\n");
    
    sb.append("  userID: ").append(userID).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  redirect: ").append(redirect).append("\n");
    sb.append("  clientId: ").append(clientId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
